### ISSUE TITLE
"width" and "height" propTypes should not be required

### ISSUE THREAD

**Issue by dekked** [vn38minhtran/react-lazysizes#10]
They don't seem to be in https://github.com/aFarkas/lazysizes, like in the second example here: https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps

**Comment by minhtranite** [comment]
Resolved on version [1.0.0](https://github.com/vn38minhtran/react-lazysizes/releases/tag/v1.0.0)
