### ISSUE TITLE
Use lazysizes add/remove class

### ISSUE THREAD

**Issue by simonsmith** [vn38minhtran/react-lazysizes#9]
To allow support in browsers that don't have `classList` (mainly IE9) it would be great to make use of the lazysizes add/remove and has class methods.

https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L691-L693

**Comment by minhtranite** [comment]
Resolved on version [1.0.0](https://github.com/vn38minhtran/react-lazysizes/releases/tag/v1.0.0)

**Comment by simonsmith** [comment]
👍
